### PR TITLE
Add api generic funcs

### PR DESCRIPTION
**Pull request by rob05c**
We might ought to discuss how we feel about this.

There's no good answer; only a question of which is the lesser evil. Using Reflection for generics is run-time and not type-safe. A code generator is hard to read. If we consider the generated code as "code," it's duplicate.

Personally, I'm leaning toward the generics. If we isolate them, and keep them in their own package, we can kind of 'quarantine' the type-unsafety. It's also one less build step, if we eliminate the generator entirely (I'm still trying to figure out if that's possible, or desirable). There's nothing wrong with code generation in general, but Go doesn't have any tools to do it, so you have to print strings, which is kind of hard to read. And even if it's generated, the api still _looks_ very duplicate. I could be being irrational there. My 2¢.

Also, for what it's worth, these last few days changed my opinion about `interface{}`. I still think it's bad, but I've become convinced it's necessary in complex things.

Thoughts?

### CODE REVIEW

**Comment by knutsel** [comment]
I have to look at this later when I'm not all sniffles and headache.... But, my first impression is that we're on a slippery slope back to the way Crystal was doing things... really smart code that's actually too clever for it's own good. 

Yes the way I did it had a lot of duplicate code, but I think you'd be surprised at how often we'll have to go into those duplicate files and edit them for exceptions... 

I dunno... Want to get some others to weigh in on this as well.

**Comment by knutsel** [comment]
Also, I think it's going to be much harder to keep the swagger stuff in sync / correct as we evolve this way. The way you do it, when we add a column there is no need to change code, but there is a need to change the swagger docs right? Guess how that'll go.

**Comment by PSUdaemon** [comment]
I'm not really excited about this change. We still have all those stub functions and less understandable reflection code. I think Jan is also right about all the little "one off's" we will need as time goes on. If we could get rid of files entirely I might be more open to this.

We can probably make the queries a little prettier. Maybe some helper functions?

**Comment by PSUdaemon** [comment]
Also, can we somehow leverage [this](https://blog.golang.org/generate) to make the code generation a little cleaner?

**Comment by dewrich** [comment]
I agree with no code generation because when there is a problem you always have to dive into the generated code to troubleshoot which can be difficult.  Having developed for many years with another static programming language that starts with a "J" this problem was the toughest to solve.  

I tend to be more practical about, try building out a few use cases with it then hold a review to get a consensus.  You can theorize forever (analysis paralysis) without building anything, but you have to make sure there are "layers" to make it easy to switch out.

I also tend to shy away from homegrown because this is not a unique problem to us.

**Comment by rob05c** [comment]
Go generate does seem like the best long-term solution for this kind of thing, but people seem to think you have to parse the AST to do it right. Which is about as painful as Reflection (though more typesafe). 

We could also look into a dependency like [gen](https://clipperhouse.github.io/gen/), if we found we needed generics often.

**Comment by dewrich** [comment]
Interesting article on this topic, a bit long but may help us decide: http://www.hydrogen18.com/blog/golang-orms-and-why-im-still-not-using-one.html

**Comment by dewrich** [comment]
@knutsel The code isn't perfect but I have to commend you on the effort to making your code more "modular".  A few methods that were long looked more out of necessity, but at least it'll make the code easier to refactor!

**Comment by PSUdaemon** [comment]
@dewrich that is a good article and definitely covers a lot of my views on SQL, strongly typed languages, and ORM's.

**Comment by dewrich** [comment]
@PSUdaemon In that vain, this guy seems to be on that track: https://github.com/variadico/scaneo

**Comment by knutsel** [comment]
This is all interesting discussion, but... 

1) I think we know we want to do a one-time gen of code so we have a starting point, but from there on out we edit the genned files as if they're real code, and we don't go back and regen. We may use the generator for adding new tables / views, but they'll be cut-and-paste, not generate and replace. Right?

2) We need a decision on the generic\* funcs... Do we want to use that or not? For example, for postCachegroup:

https://github.com/knutsel/playground/pull/4/files#diff-d1c8869b0a5e62d56e73e317b72d1be2L139

Do we the specific SQL (that is generated in our one-time gen) specified in that func there (this PR is taking that out), or do we want it to use the genericPut func that this PR is putting in

https://github.com/knutsel/playground/pull/4/files#diff-3dc4c885f9e56b2caa03001d9efd13d9R146

I'm still leaning towards the former. I think this is an important decision we should try to get consensus on.

**Comment by PSUdaemon** [comment]
I like the specific generated code and not the generic code. I feel more confident about that position after reading that article too.

**Comment by rob05c** [comment]
I'm fine with generation if that's the consensus. I was leaning toward generics, but not strongly. I'm not convinced any solution is significantly better than the others.

**Comment by dewrich** [comment]
If HAL/HATEOAS is not your cup of tea, I am for any standardization for our API: 

JSON API:
http://www.programmableweb.com/news/new-json-api-specification-aims-to-speed-api-development/2015/06/10

http://oredev.org/2015/sessions/json-api-your-anti-bikeshedding-weapon

http://jsonapi.org/implementations/

**Comment by rob05c** [comment]
Ok, I'm closing this so I can revert my fork. If we want to do anything with this in the future, I've saved the code at https://gist.github.com/robert-butts/dc26a42e7753e80ecf6b

**Pull request closed without merging**
